
service: MemberServices${self:custom.config.serviceSuffix}

custom:
  config: ${file(../../serverless-config_generated.json)}
  functionPrefix: ${self:custom.config.stage}-${self:service}-

plugins:
  - serverless-delete-loggroups

provider:
  name: aws
  runtime: nodejs4.3
  stage: ${self:custom.config.stage}
  profile: serverless-dev
  region: us-east-1
  role: arn:aws:iam::056701433599:role/lambda_basic_execution
  cfLogs: true

package:
  include: []
  exclude:
    - '*.ts'

functions:
  authorizerFunc:
    name: ${self:custom.functionPrefix}authorizerFunc
    handler: lambda-functions/authorizer-func/handler_generated.handler

  createChannel:
    name: ${self:custom.functionPrefix}createChannel
    handler: lambda-functions/create-channel/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/channels
          method: post
          cors: true
          authorizer: authorizerFunc

  createTeam:
    name: ${self:custom.functionPrefix}createTeam
    handler: lambda-functions/create-team/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/teams
          method: post
          cors: true
          authorizer: authorizerFunc

  createUser:
    name: ${self:custom.functionPrefix}createUser
    handler: lambda-functions/create-user/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/users
          method: post
          cors: true
          authorizer: authorizerFunc

  generateHttpError:
    name: ${self:custom.functionPrefix}generateHttpError
    handler: lambda-functions/generate-http-error/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/echo/error/{errorCode}
          method: get
          cors: true
          authorizer: authorizerFunc

  helloWorld:
    name: ${self:custom.functionPrefix}helloWorld
    handler: lambda-functions/hello-world/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/echo/hello-world
          method: post
          authorizer: authorizerFunc
          cors: true
      - http:
          path: /{apiVersion}/echo/hello-world
          method: get
          cors: true
          authorizer: authorizerFunc

  getChannelById:
    name: ${self:custom.functionPrefix}getChannelById
    handler: lambda-functions/get-channel-by-id/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/channels/{channelId}
          method: get
          cors: true
          authorizer: authorizerFunc

  getChannelsInTeam:
    name: ${self:custom.functionPrefix}getChannelsInTeam
    handler: lambda-functions/get-channels-in-team/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/teams/{teamId}/channels
          method: get
          cors: true
          authorizer: authorizerFunc

  getAnnouncementsInChannel:
    name: ${self:custom.functionPrefix}getAnnouncementsInChannel
    handler: lambda-functions/get-announcements-in-channel/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/channels/{channelId}/announcements
          method: get
          cors: true
          authorizer: authorizerFunc

  getAnnouncementsInTeam:
    name: ${self:custom.functionPrefix}getAnnouncementsInTeam
    handler: lambda-functions/get-announcements-in-team/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/teams/{teamId}/announcements
          method: get
          cors: true
          authorizer: authorizerFunc

  getDiscussionsInChannel:
    name: ${self:custom.functionPrefix}getDiscussionsInChannel
    handler: lambda-functions/get-discussions-in-channel/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/channels/{channelId}/discussions
          method: get
          cors: true
          authorizer: authorizerFunc

  getDiscussionsInTeam:
    name: ${self:custom.functionPrefix}getDiscussionsInTeam
    handler: lambda-functions/get-discussions-in-team/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/teams/{teamId}/discussions
          method: get
          cors: true
          authorizer: authorizerFunc

  getTasksInChannel:
    name: ${self:custom.functionPrefix}getTasksInChannel
    handler: lambda-functions/get-tasks-in-channel/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/channels/{channelId}/tasks
          method: get
          cors: true
          authorizer: authorizerFunc

  getTasksInTeam:
    name: ${self:custom.functionPrefix}getTasksInTeam
    handler: lambda-functions/get-tasks-in-team/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/teams/{teamId}/tasks
          method: get
          cors: true
          authorizer: authorizerFunc

  getUserDataById:
    name: ${self:custom.functionPrefix}getUserDataById
    handler: lambda-functions/get-user-data-by-id/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/user-data/{userDataId}
          method: get
          cors: true
          authorizer: authorizerFunc

  getUsersInChannel:
    name: ${self:custom.functionPrefix}getUsersInChannel
    handler: lambda-functions/get-users-in-channel/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/channels/{channelId}/users
          method: get
          cors: true
          authorizer: authorizerFunc

  getTeamById:
    name: ${self:custom.functionPrefix}getTeamById
    handler: lambda-functions/get-team-by-id/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/teams/{teamId}
          method: get
          cors: true
          authorizer: authorizerFunc

  getTeamByNameAndCode:
    name: ${self:custom.functionPrefix}getTeamByNameAndCode
    handler: lambda-functions/get-team-by-name-and-code/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/teams/name/{teamName}/code/{teamCode}
          method: get
          cors: true
          authorizer: authorizerFunc

  getSession:
    name: ${self:custom.functionPrefix}getSession
    handler: lambda-functions/get-session/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/teams/{teamId}/users/{userId}/session
          method: get
          cors: true
          authorizer: authorizerFunc

  getUsersInTeam:
    name: ${self:custom.functionPrefix}getUsersInTeam
    handler: lambda-functions/get-users-in-team/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/teams/{teamId}/users
          method: get
          cors: true
          authorizer: authorizerFunc

  getUserDataForTeamAndUser:
    name: ${self:custom.functionPrefix}getUserDataForTeamAndUser
    handler: lambda-functions/get-user-data-for-team-and-user/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/teams/{teamId}/users/{userId}/user-data
          method: get
          cors: true
          authorizer: authorizerFunc

  getUserById:
    name: ${self:custom.functionPrefix}getUserById
    handler: lambda-functions/get-user-by-id/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/users/{userId}
          method: get
          cors: true
          authorizer: authorizerFunc

  inviteToChannel:
    name: ${self:custom.functionPrefix}inviteToChannel
    handler: lambda-functions/invite-to-channel/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/channels/{channelId}/users
          method: put
          cors: true
          authorizer: authorizerFunc

  joinTeam:
    name: ${self:custom.functionPrefix}joinTeam
    handler: lambda-functions/join-team/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/teams/name/{teamName}/code/{teamCode}/users/{userId}
          method: put
          cors: true
          authorizer: authorizerFunc

  leaveChannel:
    name: ${self:custom.functionPrefix}leaveChannel
    handler: lambda-functions/leave-channel/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/channels/{channelId}/users/{userId}
          method: delete
          cors: true
          authorizer: authorizerFunc

  leaveTeam:
    name: ${self:custom.functionPrefix}leaveTeam
    handler: lambda-functions/leave-team/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/teams/{teamId}/users/{userId}
          method: delete
          cors: true
          authorizer: authorizerFunc

  updateUser:
    name: ${self:custom.functionPrefix}updateUser
    handler: lambda-functions/update-user/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/users/{userId}
          method: patch
          cors: true
          authorizer: authorizerFunc
