
service: CommunicationServices${self:custom.config.serviceSuffix}

custom:
  config: ${file(../../serverless-config_generated.json)}
  functionPrefix: ${self:custom.config.stage}-${self:service}-

plugins:
  - serverless-delete-loggroups

provider:
  name: aws
  runtime: nodejs4.3
  stage: ${self:custom.config.stage}
  profile: serverless-dev
  region: us-east-1
  role: arn:aws:iam::056701433599:role/lambda_basic_execution
  cfLogs: true

package:
  include: []
  exclude:
    - '*.ts'

functions:
  authorizerFunc:
    name: ${self:custom.functionPrefix}authorizerFunc
    handler: lambda-functions/authorizer-func/handler_generated.handler

  createAnnouncement:
    name: ${self:custom.functionPrefix}createAnnouncement
    handler: lambda-functions/create-announcement/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/announcements
          method: post
          cors: true
          authorizer: authorizerFunc

  createDiscussion:
    name: ${self:custom.functionPrefix}createDiscussion
    handler: lambda-functions/create-discussion/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/discussions
          method: post
          cors: true
          authorizer: authorizerFunc

  deleteAnnouncement:
    name: ${self:custom.functionPrefix}deleteAnnouncement
    handler: lambda-functions/delete-announcement/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/announcements/{announcementId}
          method: delete
          cors: true
          authorizer: authorizerFunc

  deleteDiscussion:
    name: ${self:custom.functionPrefix}deleteDiscussion
    handler: lambda-functions/delete-discussion/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/discussions/{discussionId}
          method: delete
          cors: true
          authorizer: authorizerFunc

  generateHttpError:
    name: ${self:custom.functionPrefix}generateHttpError
    handler: lambda-functions/generate-http-error/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/echo/error/{errorCode}
          method: get
          cors: true
          authorizer: authorizerFunc

  getAnnouncementById:
    name: ${self:custom.functionPrefix}getAnnouncementById
    handler: lambda-functions/get-announcement-by-id/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/announcements/{announcementId}
          method: get
          cors: true
          authorizer: authorizerFunc

  getDiscussionById:
    name: ${self:custom.functionPrefix}getDiscussionById
    handler: lambda-functions/get-discussion-by-id/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/discussions/{discussionId}
          method: get
          cors: true
          authorizer: authorizerFunc

  getNotifications:
    name: ${self:custom.functionPrefix}getNotifications
    handler: lambda-functions/get-notifications/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/notifications
          method: post
          cors: true
          authorizer: authorizerFunc

  helloWorld:
    name: ${self:custom.functionPrefix}helloWorld
    handler: lambda-functions/hello-world/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/echo/hello-world
          method: post
      - http:
          path: /{apiVersion}/echo/hello-world
          method: get
