
service: ActionServices${self:custom.config.serviceSuffix}

custom:
  config: ${file(../../serverless-config_generated.json)}
  functionPrefix: ${self:custom.config.stage}-${self:service}-

plugins:
  - serverless-delete-loggroups

provider:
  name: aws
  runtime: nodejs4.3
  stage: ${self:custom.config.stage}
  profile: serverless-dev
  region: us-east-1
  role: arn:aws:iam::056701433599:role/lambda_basic_execution
  cfLogs: true

package:
  include: []
  exclude:
    - '*.ts'

functions:
  authorizerFunc:
    name: ${self:custom.functionPrefix}authorizerFunc
    handler: lambda-functions/authorizer-func/handler_generated.handler

  fetchUpdates:
    name: ${self:custom.functionPrefix}fetchUpdates
    handler: lambda-functions/fetch-updates/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/fetchUpdates
          method: patch
          cors: true
          authorizer: authorizerFunc

  generateHttpError:
    name: ${self:custom.functionPrefix}generateHttpError
    handler: lambda-functions/generate-http-error/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/echo/error/{errorCode}
          method: get
          cors: true
          authorizer: authorizerFunc

  helloWorld:
    name: ${self:custom.functionPrefix}helloWorld
    handler: lambda-functions/hello-world/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/echo/hello-world
          method: post
      - http:
          path: /{apiVersion}/echo/hello-world
          method: get

  markSeen:
    name: ${self:custom.functionPrefix}markSeen
    handler: lambda-functions/mark-seen/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/markSeen
          method: patch
          cors: true
          authorizer: authorizerFunc

  markUnseen:
    name: ${self:custom.functionPrefix}markUnseen
    handler: lambda-functions/mark-unseen/handler_generated.handler
    events:
      - http:
          path: /{apiVersion}/markUnseen
          method: patch
          cors: true
          authorizer: authorizerFunc

  # muteContentById:
  #   name: ${self:custom.functionPrefix}muteContentById
  #   handler: lambda-functions/mute-content-by-id/handler_generated.handler
  #   events:
  #     - http:
  #         path: /{apiVersion}/muteContentById
  #         method: patch
  #         cors: true
  #         authorizer: authorizerFunc
  #
  # unmuteContentById:
  #   name: ${self:custom.functionPrefix}unmuteContentById
  #   handler: lambda-functions/unmute-content-by-id/handler_generated.handler
  #   events:
  #     - http:
  #         path: /{apiVersion}/unmuteContentById
  #         method: patch
  #         cors: true
  #         authorizer: authorizerFunc
